export const DATA_COUNTRIES = "DATA_COUNTRIES";
export const SELECTED_COUNTRIES = "SELECTED_COUNTRIES";
export const DELETE_CHARACTER_SEARCH = "DELETE_CHARACTER_SEARCH";
export const FILL_BACKUP = "FILL_BACKUP";